name: bitumen_hub
description: "Bitumen Hub - A comprehensive logistics solution for bitumen transportation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Network & API
  dio: ^5.4.0
  http: ^0.13.6
  http_parser: ^4.0.2
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location & Maps
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.20-nullsafety.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.0
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Notifications
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  flutter_timezone: ^2.0.0
  
  # File Operations
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  path_provider: ^2.1.1
  path: ^1.8.3
  mime: ^1.0.4
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  pinput: ^3.0.1
  country_code_picker: ^3.0.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

# Flutter configuration
flutter:
  uses-material-design: true
  generate: true
  
  # Fonts configuration - Uncomment and configure if you have custom fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  
  # Assets configuration
  assets:
    - assets/
    - .env